markdown: kramdown
highlighter: rouge
permalink: pretty

# Title
name: Asha Empire Online

baseurl: '/.github/profile'

github_pages:
  - sorting_algos
  - character_encoder
  - asha-empire.github.io
